# Changelog

## [Unreleased](https://github.com/confy-security/app/tree/HEAD)

[Full Changelog](https://github.com/confy-security/app/compare/f49e0d83fccdb31213d50b5d3a7c7dfad073681e...HEAD)

**Closed issues:**

- Configurar CI que executará as ferramentas Ruff, Radon e Bandit após cada push ou abertura de pull request [\#6](https://github.com/confy-security/app/issues/6)
- aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa [\#5](https://github.com/confy-security/app/issues/5)
- Modelo Canva [\#4](https://github.com/confy-security/app/issues/4)

**Merged pull requests:**

- Adicionando interface gráfica QT com PySide6, e contrução de instalador nativo com Briefcase [\#8](https://github.com/confy-security/app/pull/8) ([henriquesebastiao](https://github.com/henriquesebastiao))
- Adicionando checagem de qualidade de código via CI [\#7](https://github.com/confy-security/app/pull/7) ([henriquesebastiao](https://github.com/henriquesebastiao))



\* *This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)*
