[project]
name = "app"
version = "0.1.0"
description = "Aplicativo desktop para o sistema Confy de comunicação criptografada."
authors = [
    {name = "Henrique Sebastião",email = "contato@henriquesebastiao.com"},
    {name = "Valério Gonçalves",email = "valeriogoncalvesdev@gmail.com"},
    {name = "Lucas Sousa",email = "lucasofc-15@outlook.com"},
    {name = "Wanderson Amorim",email = "wandersonfla100@hotmail.com"},
    {name = "Emanuel Chagas",email = "pinheiroemanuel192@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "pyside6 (>=6.9.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.4"
taskipy = "^1.14.1"
radon = "^6.0.1"
bandit = "^1.8.6"
pytest-qt = "^4.5.0"
pytest-cov = "^6.2.1"
pyinstaller = "^6.14.2"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.ruff.lint.per-file-ignores]
'connect_to_server.py' = ['W293']

[tool.taskipy.tasks]
lint = 'ruff check .; ruff check . --diff'
format = 'ruff format .; ruff check . --fix'
radon = 'radon cc ./app -a -na'
bandit = 'bandit -r ./app'
run = 'poetry run python app/main.py'
test = 'poetry run pytest -s -x --cov=app -vv; poetry run coverage html'
build = 'poetry run pyinstaller app/main.py --onefile --clean --name confy --add-data="resources/icons/shield.svg:resources/icons" --windowed --icon resources/icons/icon.ico'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'
qt_api = 'pyside6'

[tool.coverage.run]
branch = true
omit = ["main.py", "utils.py"]
